In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup as bs
from requests.adapters import HTTPAdapter
import re
import numpy as np
import json

In [3]:
sID = "1201"
year = "2018"
season = "3"

"https://mops.twse.com.tw/server-java/t164sb01?step=1&CO_ID=2505&SYEAR=2018&SSEASON=4&REPORT_ID=C"

url = f"https://mops.twse.com.tw/server-java/t164sb01?step=1&CO_ID={sID}&SYEAR={year}&SSEASON={season}&REPORT_ID=C"
res = requests.get(url)
res.encoding = 'big5'
soup = bs(res.text, "lxml")
tables = soup.select('table')

season = f"{year}_Q{season}"

# Ntable = 1 #資產負債表
# Ntable = 2 #綜合損益表
# Ntable = 3 #現金流量表
# Ntable = 4 #當期權益變動表

# BalanceSheet

In [4]:
Ntable = 1
tr_list = tables[Ntable].select("tr")
# print(tr_list)
tbl = []
for tr in tr_list:
#     print(tr)
    td_list = tr.select('td')
#     print(td_list)
    if len(td_list) != 0:
        row = []
        for i in td_list:
            row.append(i.text.strip().replace(",",''))
#             print(i.text.strip().replace(",",''))
        if len(row) > 0:
            tbl.append(row[:2])
        
print(tbl)        
df = pd.DataFrame(tbl, columns = ['cht','value'])
df = df[df['value'] != '']
# df

[['資產', ''], ['流動資產', ''], ['現金及約當現金', '3059098'], ['透過損益按公允價值衡量之金融資產－流動', '0'], ['應收票據淨額', '65411'], ['應收帳款淨額', '3150483'], ['應收帳款－關係人淨額', '249249'], ['其他應收款', '842662'], ['本期所得稅資產', '402'], ['存貨', '1237780'], ['預付款項', '342123'], ['其他流動資產', '271746'], ['流動資產合計', '9218954'], ['非流動資產', ''], ['透過損益按公允價值衡量之金融資產－非流動', '33443'], ['備供出售金融資產－非流動', '0'], ['採用權益法之投資', '23257'], ['不動產、廠房及設備', '11038874'], ['投資性不動產淨額', '163519'], ['無形資產', '131490'], ['生物資產－非流動', '162351'], ['遞延所得稅資產', '1260748'], ['其他非流動資產', '352964'], ['非流動資產合計', '13166646'], ['資產總計', '22385600'], ['負債及權益', ''], ['負債', ''], ['流動負債', ''], ['短期借款', '5003497'], ['應付短期票券', '348978'], ['透過損益按公允價值衡量之金融負債－流動', '9'], ['合約負債－流動', '65808'], ['應付票據', '3361'], ['應付帳款', '1844520'], ['應付帳款－關係人', '83176'], ['應付建造合約款', '0'], ['其他應付款', '2428559'], ['本期所得稅負債', '114163'], ['其他流動負債', '184692'], ['流動負債合計', '10076763'], ['非流動負債', ''], ['長期借款', '4492000'], ['遞延所得稅負債', '1177950'], ['其他非流動負債', '490087'], ['非流動負債合計', '6160037'], ['負債總計', '16236800'], ['權益', ''], ['歸屬於母公司業主之權益', ''], ['股本', ''], ['普通股股本', '5060629'], ['股本合計', '5060629'], ['資本公積', ''], ['資本公積－其他', '688'], ['資本公積合計', '688'], ['保留盈餘', ''], ['法定盈餘公積', '475607'], ['未分配盈餘（或待彌補虧損）', '807709'], ['保留盈餘合計', '1283316'], ['其他權益', ''], ['國外營運機構財務報表換算之兌換差額', '-207979'], ['備供出售金融資產未實現損益', '0'], ['其他權益合計', '-207979'], ['歸屬於母公司業主之權益合計', '6136654'], ['非控制權益', '12146'], ['權益總計', '6148800'], ['負債及權益總計', '22385600'], ['待註銷股本股數', '0'], ['預收股款（權益項下）之約當發行股數', '0'], ['母公司暨子公司所持有之母公司庫藏股股數（單位：股）', '0']]

# ProfitLoss

In [5]:
Ntable = 2
tr_list = tables[Ntable].select("tr")
# print(tr_list)
tbl = []
for tr in tr_list:
#     print(tr)
    td_list = tr.select('td')
#     print(td_list)
    if len(td_list) != 0:
        row = []
        for i in td_list:
            row.append(i.text.strip().replace(",",''))
#             print(i.text.strip().replace(",",''))
        if len(row) > 0:
            tbl.append(row[:2])
        
tbl        
df = pd.DataFrame(tbl, columns = ['cht','value'])
df = df[df['value'] != '']
df

                       cht    value
1                   營業收入合計  5680844
3                   營業成本合計  3775805
4                 營業毛利（毛損）  1905039
5               營業毛利（毛損）淨額  1905039
7                     推銷費用  1261861
8                     管理費用   248237
9                   研究發展費用    63367
10            預期信用減損損失(利益)      915
11                  營業費用合計  1574380
12                營業利益（損失）   330659
15                  其他收入合計    42131
17               其他利益及損失淨額   834131
19                  財務成本淨額    61532
21  採用權益法認列之關聯企業及合資損益之份額淨額    -3060
22              營業外收入及支出合計   811670
23          繼續營業單位稅前淨利（淨損）  1142329
25             所得稅費用（利益）合計   183758
26          繼續營業單位本期淨利（淨損）   958571
27                本期淨利（淨損）   958571
30       國外營運機構財務報表換算之兌換差額  -114090
31         與可能重分類之項目相關之所得稅        0
32         後續可能重分類至損益之項目總額  -114090
33              其他綜合損益（淨額）  -114090
34                本期綜合損益總額   844481
36             母公司業主（淨利／損）   958449
37             非控制權益（淨利／損）      122
39             母公司業主（綜合損益）   844674
40             非控制權益（綜合損益）     -193
42            繼續營業單位淨利（淨損）     1.89
43                基本每股盈餘合計     1.89
45            繼續營業單位淨利（淨損）     1.89
46                稀釋每股盈餘合計     1.89

# Cashflow table

In [6]:
Ntable = 3
tr_list = tables[Ntable].select("tr")
# print(tr_list)

tbl = []
for tr in tr_list:
#     print(tr)
    td_list = tr.select("td")
    if len(td_list) != 0:
        row = []
        for i in td_list:
            row.append(i.text.strip().replace(',',''))
#             print(i.text.strip().replace(',',''))
#     print(tr.select("td"))
        if len(row) > 0:
            tbl.append(row[:2])
    
tbl
df = pd.DataFrame(tbl, columns = ['cht','value'])
df = df[df['value'] != '']
df

                            cht    value
1                繼續營業單位稅前淨利（淨損）  1009984
2                    本期稅前淨利（淨損）  1009984
5                          折舊費用   665751
6                          攤銷費用    10578
7   預期信用減損損失（利益）數／呆帳費用提列（轉列收入）數      329
..                          ...      ...
68              匯率變動對現金及約當現金之影響   101606
69             本期現金及約當現金增加（減少）數   295305
70                  期初現金及約當現金餘額  2763793
71                  期末現金及約當現金餘額  3059098
72              資產負債表帳列之現金及約當現金  3059098

[65 rows x 2 columns]

# Equity table

In [10]:
Ntable = 4
tr_list = tables[Ntable].select("tr")
# print(tr_list)
print(len(tables[Ntable].select("tr")))

tbl = []
column = []
for tr in tr_list:
    td_list = tr.select("td") #row
#     print(td_list)
    th_list = tr.select("th") #column
#     print(th_list)
    row = []
    for td in td_list:
#         print(td.text.strip().replace("\n",""))
        row.append(td.text.strip().replace("\n","").replace(",",""))
    if len(row) > 0:
        tbl.append(row)
    
    for th in th_list:
        print(th)
        column.append(th.text.strip().replace("\n",""))
#         print(th.text.strip().replace("\n",""))

# print(column)
# print(tbl)

df_dict = {'col_index':column,'row_value':tbl}
df = pd.DataFrame(tbl,columns = column)
df = df.replace("", np.nan)
df = df.fillna(0)

df['items'] = df.iloc[:,0]
df = df.iloc[:,1:]
df.set_index('items', inplace=True)
# print(df.info())
# print(df_dict)

10
<th nowrap=""></th>
<th nowrap="">普通股股本</th>
<th nowrap="">股本合計</th>
<th nowrap="">資本公積</th>
<th nowrap="">法定盈餘公積</th>
<th nowrap="">未分配盈餘（或待彌補虧損）</th>
<th nowrap="">保留盈餘合計</th>
<th nowrap="">國外營運機構財務報表換算之兌換差額</th>
<th nowrap="">備供出售金融資產未實現利益（損失）</th>
<th nowrap="">其他權益項目合計</th>
<th nowrap="">歸屬於母公司業主之權益總計</th>
<th nowrap="">非控制權益</th>
<th nowrap="">權益總額</th>

In [ ]:
data = pd.read_html('https://mops.twse.com.tw/server-java/t164sb01?step=1&CO_ID=2505&SYEAR=2018&SSEASON=4&REPORT_ID=C')

In [ ]:
data[1]

# Test

In [ ]:
keyword={'sid':'1413', 'y':'2018', 's':'4', 'rid':"A"}
header= {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36'}
url='https://mops.twse.com.tw/server-java/t164sb01?step=1&CO_ID={sid}&SYEAR={y}&SSEASON={s}&REPORT_ID={rid}'.format(**keyword)
URL = 'https://mops.twse.com.tw/server-java/t164sb01?step=1&CO_ID=1413&SYEAR=2018&SSEASON=4&REPORT_ID=A'

web_ss = requests.session()
ss_adapter = HTTPAdapter(max_retries=3)
web_ss.mount("https://", adapter=ss_adapter)
res = web_ss.get(url=URL, headers=header, timeout=5)
res.encoding = 'big5'

try:
    if res.status_code == 200:
        #soup = bs4(res.text, "lxml")
        soup = bs(res.text, "html.parser")
        tables = soup.select('table')
except Exception as e:
    print(e)
    
print(len(tables))